import { NextResponse } from "next/server";
import { db } from "@/lib/db";

// One-time seed endpoint — call once after deployment, then it self-disables
export async function POST(req: Request) {
  const secret = req.headers.get("x-seed-secret");
  if (secret !== process.env.SEED_SECRET) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const existing = await db.course.count();
  if (existing > 0) {
    return NextResponse.json({ message: "Already seeded", courses: existing });
  }

  const mathTeacher = await db.user.upsert({
    where: { email: "math@rnda.org.za" },
    update: {},
    create: { name: "Ms. Khumalo", email: "math@rnda.org.za", role: "TEACHER" },
  });
  const scienceTeacher = await db.user.upsert({
    where: { email: "science@rnda.org.za" },
    update: {},
    create: { name: "Mr. Dlamini", email: "science@rnda.org.za", role: "TEACHER" },
  });
  const techTeacher = await db.user.upsert({
    where: { email: "tech@rnda.org.za" },
    update: {},
    create: { name: "Ms. Nkosi", email: "tech@rnda.org.za", role: "TEACHER" },
  });

  const coursesData = [
    { title: "Introduction to Numbers and Operations", description: "Build a solid foundation in whole numbers, fractions, and basic operations.", subject: "MATHEMATICS", grade: 5, teacherId: mathTeacher.id, published: true, lessons: [{ title: "Understanding Whole Numbers", content: "Whole numbers are the counting numbers starting from 0: 0, 1, 2, 3...\n\nIn this lesson we explore:\n- Place value (ones, tens, hundreds, thousands)\n- Reading and writing large numbers\n- Comparing and ordering numbers\n\nActivity: Write the number 4,372 in words and identify the place value of each digit.", duration: 30 }, { title: "Addition and Subtraction", content: "Addition combines two or more numbers to find the total.\nSubtraction finds the difference between numbers.\n\nKey strategies:\n- Column method for large numbers\n- Estimation before calculating\n- Checking answers by reversing the operation\n\nPractice: Calculate 5,847 + 3,264 and 9,000 - 4,356.", duration: 35 }, { title: "Introduction to Fractions", content: "A fraction represents a part of a whole.\n\nParts of a fraction:\n- Numerator: the top number (how many parts we have)\n- Denominator: the bottom number (total equal parts)\n\nExample: 3/4 means 3 out of 4 equal parts.", duration: 40 }] },
    { title: "Basic Life Science: Plants and Animals", description: "Discover the living world — from plant cells to animal adaptations.", subject: "LIFE_SCIENCE", grade: 5, teacherId: scienceTeacher.id, published: true, lessons: [{ title: "What Makes Something Alive?", content: "Living things share common characteristics:\n1. They grow and develop\n2. They reproduce\n3. They respond to their environment\n4. They need food, water, and air\n5. They are made of cells", duration: 25 }, { title: "Plant Parts and Their Functions", content: "Every plant has key parts with specific jobs:\n\n🌱 ROOTS: Absorb water and minerals from soil\n🌿 STEM: Transports water and nutrients\n🍃 LEAVES: Make food using sunlight (photosynthesis)\n🌸 FLOWERS: Reproduction\n🍎 FRUITS/SEEDS: Protect and spread seeds", duration: 30 }, { title: "Animal Adaptations", content: "Adaptations are special features that help animals survive in their environment.\n\nExamples:\n- A camel's hump stores fat for energy in the desert\n- A fish has gills to breathe underwater\n- A chameleon changes color to camouflage itself", duration: 35 }] },
    { title: "Geometry and Measurement", description: "Master shapes, angles, perimeter, area, and volume.", subject: "MATHEMATICS", grade: 6, teacherId: mathTeacher.id, published: true, lessons: [{ title: "2D Shapes and Their Properties", content: "Two-dimensional shapes are flat shapes with length and width.\n\nKey shapes:\n- Triangle: 3 sides, 3 angles (sum = 180°)\n- Rectangle: 4 sides, all angles = 90°\n- Circle: no straight sides\n- Hexagon: 6 equal sides", duration: 30 }, { title: "Perimeter and Area", content: "PERIMETER is the total distance around a shape.\nAREA is the amount of space inside a shape.\n\nFormulas:\nRectangle: P = 2(l + w), A = l × w\nTriangle: P = a + b + c, A = ½ × base × height", duration: 40 }, { title: "Introduction to Volume", content: "Volume measures the amount of 3D space an object occupies.\n\nVolume of a rectangular prism:\nV = length × width × height\n\nExample: A box is 4 cm × 3 cm × 2 cm\nV = 4 × 3 × 2 = 24 cm³", duration: 35 }] },
    { title: "Introduction to Algebra", description: "Unlock the language of mathematics — variables, expressions, and equations.", subject: "MATHEMATICS", grade: 7, teacherId: mathTeacher.id, published: true, lessons: [{ title: "Variables and Expressions", content: "In algebra, a VARIABLE is a letter that represents an unknown number.\n\nAn EXPRESSION is a combination of numbers, variables, and operations:\n- 3x (3 times x)\n- 2a + 5\n\nSimplifying: Collect like terms.\n3x + 2x + 4 = 5x + 4", duration: 35 }, { title: "Solving Linear Equations", content: "An EQUATION says two things are equal.\n\nGolden rule: Whatever you do to one side, do to the other side.\n\nExample: 2x + 3 = 11\nSubtract 3: 2x = 8\nDivide by 2: x = 4\n\nCheck: 2(4) + 3 = 11 ✓", duration: 40 }, { title: "Patterns and Sequences", content: "A SEQUENCE is an ordered list of numbers following a pattern.\n\nArithmetic: add the same number each time\n2, 5, 8, 11... (add 3)\n\nGeometric: multiply by the same number\n2, 6, 18, 54... (multiply by 3)\n\nFormula: Tₙ = a + (n-1)d", duration: 35 }] },
    { title: "Atoms, Molecules and Matter", description: "Dive into the building blocks of everything around us.", subject: "PHYSICAL_SCIENCE", grade: 7, teacherId: scienceTeacher.id, published: true, lessons: [{ title: "What is Matter?", content: "Matter is anything that has mass and takes up space.\n\nStates of Matter:\n🧊 SOLID: fixed shape and volume\n💧 LIQUID: fixed volume, no fixed shape\n💨 GAS: no fixed shape or volume\n\nChanges: Melting, Evaporation, Condensation, Freezing", duration: 30 }, { title: "Atoms and the Periodic Table", content: "ATOMS are the tiny building blocks of all matter.\n\nStructure:\n⚛️ Nucleus: protons (+) and neutrons\n🔄 Electrons: orbit the nucleus (-)\n\nThe PERIODIC TABLE organises all known elements.\nH = Hydrogen, O = Oxygen, Fe = Iron", duration: 40 }, { title: "Physical and Chemical Changes", content: "PHYSICAL CHANGE: substance changes form but not composition.\nExamples: cutting paper, melting ice\n\nCHEMICAL CHANGE: a new substance is formed.\nExamples: burning wood, rusting iron\n\nSigns: color change, gas produced, temperature change", duration: 35 }] },
    { title: "Computer Science Fundamentals", description: "Learn how computers work, from binary to algorithms.", subject: "COMPUTER_SCIENCE", grade: 8, teacherId: techTeacher.id, published: true, lessons: [{ title: "How Computers Work", content: "A computer processes data using:\n\n🖥️ CPU: the brain — performs calculations\n💾 RAM: temporary storage for running programs\n💿 Storage: permanent data storage\n⌨️ Input: keyboard, mouse\n🖥️ Output: monitor, speakers", duration: 30 }, { title: "Binary and Number Systems", content: "Computers store all data as 1s and 0s — called BINARY.\n\nConverting binary to decimal:\n1011 = 1×8 + 0×4 + 1×2 + 1×1 = 11\n\nConverting decimal to binary:\n13 → 1101\n\nChallenge: Convert 42 to binary.", duration: 40 }, { title: "Introduction to Algorithms", content: "An ALGORITHM is a step-by-step set of instructions to solve a problem.\n\nProperties:\n✅ Clear and unambiguous\n✅ Has a definite start and end\n✅ Produces the correct output\n\nAlgorithms sort data, search databases, and power AI.", duration: 35 }] },
    { title: "Functions and Graphs", description: "Understand relationships between variables through functions and their graphs.", subject: "MATHEMATICS", grade: 9, teacherId: mathTeacher.id, published: true, lessons: [{ title: "What is a Function?", content: "A FUNCTION is a relationship where each input has exactly one output.\n\nf(x) = 2x + 1\nf(3) = 7, f(0) = 1, f(-2) = -3\n\nDomain = set of inputs\nRange = set of outputs", duration: 35 }, { title: "Linear Functions", content: "y = mx + c\n\nm = gradient (slope)\nc = y-intercept\n\nExample: y = 2x + 3\nGradient = 2, y-intercept = 3\n\nTo draw: plot (0,3) then use gradient to find next point.", duration: 40 }, { title: "Quadratic Functions", content: "y = ax² + bx + c — graph is a parabola.\n\nIf a > 0: opens UP ☺\nIf a < 0: opens DOWN ☹\n\nKey features: turning point, axis of symmetry, x-intercepts\n\nExample: y = x² - 4\nRoots: x = ±2, Vertex: (0, -4)", duration: 45 }] },
    { title: "Euclidean Geometry", description: "Prove geometric theorems and solve angle and circle problems.", subject: "MATHEMATICS", grade: 10, teacherId: mathTeacher.id, published: true, lessons: [{ title: "Lines, Angles and Triangles", content: "ANGLE TYPES: Acute < 90°, Right = 90°, Obtuse > 90°\n\nPARALLEL LINE ANGLES:\n- Co-interior: sum = 180°\n- Alternate: equal (Z-shape)\n- Corresponding: equal (F-shape)\n\nTRIANGLE: angles sum = 180°", duration: 40 }, { title: "Congruence and Similarity", content: "CONGRUENT ≅: same shape AND size\nSIMILAR |||: same shape, different size\n\nCongruent triangle tests: SSS, SAS, AAS, RHS\nSimilar triangle tests: AA, SSS (proportional), SAS", duration: 45 }, { title: "Circle Theorems", content: "⭕ Angle at centre = 2 × angle at circumference\n⭕ Angles in same segment are equal\n⭕ Angle in semicircle = 90°\n⭕ Opposite angles of cyclic quadrilateral = 180°\n⭕ Tangent ⊥ radius", duration: 50 }] },
    { title: "Trigonometry", description: "Master trig ratios, identities, and solving triangles.", subject: "MATHEMATICS", grade: 11, teacherId: mathTeacher.id, published: true, lessons: [{ title: "Trigonometric Ratios", content: "SOH-CAH-TOA:\nsin θ = opposite/hypotenuse\ncos θ = adjacent/hypotenuse\ntan θ = opposite/adjacent\n\nSpecial angles: 30°, 45°, 60°\nsin 30° = 1/2, cos 60° = 1/2, tan 45° = 1", duration: 40 }, { title: "Sine and Cosine Rules", content: "For NON-right triangles:\n\nSINE RULE: a/sin A = b/sin B = c/sin C\nCOSINE RULE: a² = b² + c² - 2bc·cos A\n\nUse Sine Rule when: two angles + a side\nUse Cosine Rule when: two sides + included angle", duration: 45 }, { title: "Trigonometric Identities", content: "Fundamental identities:\n1. sin²θ + cos²θ = 1\n2. tan θ = sin θ/cos θ\n\nDerived:\n- sin²θ = 1 - cos²θ\n- cos²θ = 1 - sin²θ\n\nProving: work on ONE side only, never cross multiply.", duration: 45 }] },
    { title: "Calculus: Differentiation", description: "Understand rates of change and master differentiation techniques.", subject: "MATHEMATICS", grade: 12, teacherId: mathTeacher.id, published: true, lessons: [{ title: "Limits and the Derivative", content: "The DERIVATIVE measures the rate of change.\n\nFrom first principles:\nf'(x) = lim[h→0] [f(x+h) - f(x)] / h\n\nExample: f(x) = x²\nf'(x) = 2x\n\nThe derivative = gradient of the tangent at a point.", duration: 50 }, { title: "Rules of Differentiation", content: "Power rule: d/dx(xⁿ) = nxⁿ⁻¹\nConstant: d/dx(c) = 0\nSum rule: d/dx[f+g] = f' + g'\n\nExamples:\nd/dx(x³) = 3x²\nd/dx(3x⁴ - 2x² + 7) = 12x³ - 4x", duration: 45 }, { title: "Turning Points and Optimisation", content: "f'(x) = 0 at stationary points.\n\nIf f''(x) < 0: LOCAL MAXIMUM\nIf f''(x) > 0: LOCAL MINIMUM\n\nOptimisation: write quantity as function → differentiate → set = 0 → solve\n\nExample: maximise area with fixed perimeter.", duration: 55 }] },
    { title: "Physical Science: Electricity and Magnetism", description: "Master circuits, electrostatics, and electromagnetic induction.", subject: "PHYSICAL_SCIENCE", grade: 12, teacherId: scienceTeacher.id, published: true, lessons: [{ title: "Electric Circuits and Ohm's Law", content: "OHM'S LAW: V = IR\n\nSeries: R_total = R₁ + R₂\nParallel: 1/R_total = 1/R₁ + 1/R₂\n\nPOWER: P = VI = I²R = V²/R\n\nExample: Toaster, R = 20Ω, V = 220V\nI = 220/20 = 11A, P = 220 × 11 = 2420W", duration: 50 }, { title: "Electrostatics", content: "Like charges REPEL, unlike charges ATTRACT.\n\nCOULOMB'S LAW: F = kq₁q₂/r²\nk = 9 × 10⁹ N·m²/C²\n\nELECTRIC FIELD: E = F/q = kQ/r²\n\nApplications: Lightning conductors, photocopiers, capacitors", duration: 45 }, { title: "Electromagnetic Induction", content: "FARADAY'S LAW: changing magnetic field induces EMF.\n\nε = -N × ΔΦ/Δt\n\nLENZ'S LAW: induced current opposes the change.\n\nDevices: Generator (mechanical → electrical), Transformer (changes AC voltage)\n\nSA mains: 50 Hz, 230 V", duration: 50 }] },
  ];

  let count = 0;
  for (const courseData of coursesData) {
    const { lessons, ...courseFields } = courseData;
    const course = await db.course.create({ data: courseFields });
    for (let i = 0; i < lessons.length; i++) {
      await db.lesson.create({ data: { ...lessons[i], order: i + 1, courseId: course.id } });
    }
    count++;
  }

  return NextResponse.json({ ok: true, coursesSeeded: count });
}
